version: '3.8'

services:
  # MYSQL
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: on-failure
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - mysql
  
  # POSTGRES
  pgsql:
    container_name: pgsql
    image: postgres:16.3
    restart: on-failure
    volumes:
      - ./pgsql:/var/lib/postgresql/data;
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: '${PGSQL_USER}'
      POSTGRES_PASSWORD: '${PGSQL_ROOT_PASSWORD}'
    networks:
      - pgsql

  #PHPMYADMIN
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: on-failure
    ports:
      - '9090:80'
    environment:
      PMA_HOST: 'mysql'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      UPLOAD_LIMIT: 120M
    depends_on:
      - mysql
    networks:
      - mysql

  #ADMINER
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: on-failure
    ports:
      - '9091:8080'
    depends_on:
      - mysql
      - pgsql
    networks:
      - mysql
      - pgsql

networks:
  mysql:
    name: mysql
    external: true
  pgsql:
    name: pgsql
    external: true

