version: '3.8'

services:
  # MYSQL
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: on-failure
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - mysql

  #PHPMYADMIN
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: on-failure
    ports:
      - '9090:80'
    environment:
      PMA_HOST: 'mysql'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      UPLOAD_LIMIT: 64M
    depends_on:
      - mysql
    networks:
      - mysql

networks:
  mysql:
    name: mysql
    external: true

